title = "Gitleaks Config"

# Allowlist (false positives)
[allowlist]
description = "Ignore test keys"
regexes = [
  "EXAMPLE_KEY",
  "test_.*",
  "12345"
]

# Custom rules
[[rules]]
description = "Generic API Key"
regex = '''(?i)(API|SECRET)_?KEY\s*=\s*['"]?([a-z0-9]{8,64})['"]?'''
tags = ["api-key", "hardcoded"]

[[rules]]
description = "Stripe Key"
regex = '''(?i)sk_(test|live)_[a-z0-9]{24}'''
tags = ["stripe", "payment"]