title = "Generic Gitleaks Basic Config"
version = "8.24.3"

[allowlist]
description = "Global allowlist to prevent false positives."
regexes = [
    '''EXAMPLE_KEY''', # Placeholder for known safe example keys
    '''test_.*''',     # Common prefix for test keys/secrets
    # Add other project-specific safe patterns here
]
paths = [
    '''\.md$''', # Exclude all Markdown files
    # You can add other paths to exclude here, for example:
    # '''test/data/''', # Excludes a specific directory
]

[[rules]]
id = "generic-api-key"
description = "Detects common patterns for API keys."
# Example: API_KEY = "abc123xyz789" or secretKey: 'def456uvw012'
# Looks for common API key variable names (api, secret, access, private + key, token, secret)
# followed by an alphanumeric string of 16-128 characters.
regex = '''(?i)(api|secret|access|private)_?(key|token|secret)\s*[:=]\s*['"]?([a-z0-9_\\-]{16,128})['"]?'''
secretGroup = 3 # Captures only the key value: ([a-z0-9_\\-]{16,128})
tags = ["api", "key", "token"]
severity = "high"
keywords = ["api_key", "apikey", "secret_key", "secretkey", "access_key", "accesskey", "private_key", "privatekey", "api_token", "apitoken"]

[[rules]]
id = "generic-password-assignment"
description = "Detects common password assignments in configurations."
# Looks for keywords like password, pass, token, secret, key followed by an assignment.
regex = '''(?i)\b(password|passwd|pwd|pass|token|secret|auth_key|api_key|access_key|private_key)\b\s*[:=]\s*['"]?([^\s'"`;]{5,128})['"]?'''
secretGroup = 2 # Captures only the password value.
keywords = ["password", "pass", "token", "secret", "key", "passwd", "pwd"]
tags = ["credential", "password"]
severity = "critical"

[[rules]]
id = "aws-access-key-id"
description = "AWS Access Key ID"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AROA|ASCA|ASIA)[A-Z0-9]{16}'''
tags = ["aws", "key"]
severity = "critical"
keywords = ["akia", "asca", "aroa", "agpa", "asia"]

[[rules]]
id = "aws-secret-access-key"
description = "Potential AWS Secret Access Key"
# Looks for AWS-related keywords near a 40-character Base64 string.
regex = '''(?i)\b(aws|s3|ec2|amazon)\w*_?(secret|access)_?(key|token)\b\W{0,30}['"]?([A-Za-z0-9/+=]{40})['"]?'''
secretGroup = 4 # Captures the 40-character secret part.
tags = ["aws", "secret", "key"]
severity = "critical"
keywords = ["aws_secret_access_key", "aws_secret_key", "s3_secret_key", "ec2_secret_key"]

[[rules]]
id = "private-key"
description = "Asymmetric Private Key (e.g., RSA, SSH, PGP)"
regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "asymmetric", "privatekey", "ssh", "pgp"]
severity = "critical"
