title = "Gitleaks Config"
version = "8.24.3"

[allowlist]
regexes = ["EXAMPLE_KEY", "test_.*"]

[[rules]]
id = "stripe-key"
description = "Stripe API Key"
regex = '''(?i)sk_(test|live)_[a-z0-9]{24}'''
severity = "high"

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(API|SECRET)_?KEY\s*=\s*['"]?([a-z0-9]{8,64})['"]?'''
severity = "high"