services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      # This line tells Prometheus its externally reachable URL,
      # including the subpath, so it generates correct internal links.
      - '--web.external-url=http://131.186.37.96/prometheus/'
    ports:
      - "9090:9090" # Keep for direct access if needed, NGINX will be primary
    restart: unless-stopped
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports: # Corrected indentation
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring
    environment:
      # Configure Grafana for subpath access. Replace with your actual IP or hostname if not 131.186.37.96
      - GF_SERVER_ROOT_URL=http://131.186.37.96/grafana/
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=devsecopshomelab
      - GF_USERS_ALLOW_SIGN_UP=false

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  juice-shop: # Renamed service from pygoat to juice-shop
    image: bkimminich/juice-shop:latest # Changed image
    container_name: juice-shop # Changed container name
    ports:
      - "8000:3000" # Host port 8000 maps to Juice Shop's internal port 3000
    restart: unless-stopped
    # The default command in the bkimminich/juice-shop image is usually sufficient.
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx_node_01
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - prometheus
      - grafana
      - juice-shop # Updated dependency
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: