name: Secret Scan
on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for full history scan

      - name: Run Gitleaks
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          config: .gitleaks.toml  # Path to your custom config
          report_format: sarif     # Generate SARIF report
          fail: false             # Don't fail immediately (allows SARIF upload)
          verbose: true           # Debug logs

      - name: Upload SARIF Report
        if: ${{ steps.gitleaks.outputs.exitcode == 1 }}  # Only upload if leaks found
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}