name: Secret Scan
on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to scan full git history

      - uses: gitleaks/gitleaks-action@v2
        with:
          # Optional configuration (remove these lines if not needed)
          config: .gitleaks.toml  # Path to custom config
          sarif: true           # Upload to GitHub Security tab
          version: 8.18.1              # Pin specific version